# Generated by Django 4.2.30 on 2026-05-15 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_avatar_url_user_email_notifications_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "identifier",
                    models.CharField(
                        help_text="Email/phone for transfers & airtime, meter number for bills.",
                        max_length=120,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Transfer"),
                            ("AIRTIME", "Airtime"),
                            ("BILL_PAYMENT", "Bill Payment"),
                        ],
                        default="TRANSFER",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MTN/Orange for airtime, ENEO/CAMWATER/CANAL+/CAMTEL for bills.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficiary",
                "verbose_name_plural": "Beneficiaries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Transfer"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("BILL_PAYMENT", "Bill Payment"),
                            ("AIRTIME", "Airtime"),
                            ("SECURITY", "Security"),
                            ("ACCOUNT", "Account"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.CharField(blank=True, default="", max_length=500)),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_no_user_id_b37b35_idx",
                    ),
                    models.Index(
                        fields=["user", "read"], name="accounts_no_user_id_1df518_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="beneficiary",
            constraint=models.UniqueConstraint(
                fields=("owner", "identifier", "category", "provider"),
                name="unique_beneficiary_per_owner",
            ),
        ),
    ]
