# Generated by Django 4.2.30 on 2026-05-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_phone",
            field=models.CharField(blank=True, default="", max_length=25),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_reference",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
