# Generated by Django 4.2.30 on 2026-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_add_payment_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("TRANSFER", "Transfer"),
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("BILL_PAYMENT", "Bill Payment"),
                    ("AIRTIME", "Airtime"),
                ],
                default="TRANSFER",
                max_length=20,
            ),
        ),
    ]
